SELECT * FROM ZAJECIA.DOSTAWCY;

SELECT zajecia.DOSTAWCY.NAZWAFIRMY, ZAJECIA.DOSTAWCY.ADRES, ZAJECIA.DOSTAWCY.MIASTO FROM zajecia.DOSTAWCY;

SELECT * FROM ZAJECIA.DOSTAWCY ORDER BY city DESC;

SELECT DISTINCT miasto FROM ZAJECIA.DOSTAWCY;

SELECT UPPER(nazwafirmy), miasto FROM zajecia.DOSTAWCY WHERE miasto LIKE 'Bytom';

SELECT * FROM ZAJECIA.DOSTAWCY WHERE (miasto LIKE 'Bytom' OR miasto LIKE 'Katowice');

SELECT * FROM ZAJECIA.DOSTAWCY WHERE NAZWAFIRMY LIKE 'B%';

SELECT * FROM ZAJECIA.DOSTAWCY WHERE (LENGTH(NAZWAFIRMY) >= 10);

SELECT * FROM ZAJECIA.DOSTAWCY WHERE SUBSTR(KODPOCZTOWY, 0, 2) LIKE '23';

SELECT * FROM ZAJECIA.DOSTAWCY WHERE substr(KODPOCZTOWY, 3, 2) LIKE '33'; 

SELECT * FROM ZAJECIA.PRODUKTY WHERE ILOSC < STANMINIMUM;

SELECT NAZWAPRODUKTU, (STANMINIMUM - ILOSC) AS "zakup" FROM ZAJECIA.PRODUKTY WHERE ilosc < STANMINIMUM;

SELECT p.NAZWAPRODUKTU, d.ADRES, (p.ILOSC - p.STANMINIMUM) AS "Zamowienie" FROM zajecia.PRODUKTY p 
INNER JOIN ZAJECIA.DOSTAWCY d ON p.IDDOSTAWCY = d.IDDOSTAWCY
WHERE p.ilosc - p.STANMINIMUM >= 100;

SELECT DISTINCT * FROM ZAJECIA.PRODUKTY WHERE WYCOFANY = 1;

SELECT * FROM zajecia.PRACOWNICY;

SELECT * FROM zajecia.PRACOWNICY WHERE DATAURODZENIA < '1960-01-01';

SELECT * FROM ZAJECIA.PRACOWNICY WHERE DATAURODZENIA > DATAZATRUDNIENIA;

SELECT round(AVG(placa)) FROM ZAJECIA.PRACOWNICY

SELECT min(placa), max(placa), avg(placa) FROM zajecia.PRACOWNICY;

SELECT round(avg(placa)) FROM zajecia.PRACOWNICY WHERE STANOWISKO like 'Przedstawiciel handlowy';

SELECT miasto, round(avg(placa)) FROM zajecia.PRACOWNICY GROUP BY miasto ORDER BY miasto;

SELECT miasto, count(idpracownika) FROM zajecia.PRACOWNICY GROUP BY miasto;

SELECT miasto FROM zajecia.pracownicy HAVING count(IDPRACOWNIKA) > 2 GROUP BY miasto;

SELECT NAZWISKO, MONTHS_BETWEEN('2019-10-07', dataurodzenia)/12 AS "Roznica w latach" FROM ZAJECIA.PRACOWNICY;

SELECT stanowisko, avg(MONTHS_BETWEEN('2019-10-07', dataurodzenia)/12) FROM ZAJECIA.PRACOWNICY GROUP BY stanowisko;

SELECT SELECT NAZWISKO, MONTHS_BETWEEN(ADD_MONTHS('2019-10-07', 10), dataurodzenia)/12 AS "Roznica w latach" FROM ZAJECIA.PRACOWNICY;

SELECT * FROM (SELECT * FROM ZAJECIA.PRACOWNICY ORDER BY PLACA DESC) WHERE ROWNUM < 4;

SELECT * FROM zajecia.PRODUKTY p INNER JOIN ZAJECIA.DOSTAWCY d ON p.IDDOSTAWCY = d.IDDOSTAWCY WHERE d.NAZWAFIRMY LIKE 'XYZ';

SELECT * FROM zajecia.PRODUKTY p INNER JOIN ZAJECIA.DOSTAWCY d ON p.IDDOSTAWCY = d.IDDOSTAWCY WHERE d.NAZWAFIRMY LIKE 'Polinax' AND p.ILOSC < 10;

SELECT * FROM zajecia.PRODUKTY p INNER JOIN ZAJECIA.DOSTAWCY d ON p.IDDOSTAWCY = d.IDDOSTAWCY WHERE d.MIASTO LIKE 'Bytom';

SELECT d.NAZWAFIRMY, (count(p.IDPRODUKTU)) FROM zajecia.PRODUKTY p INNER JOIN ZAJECIA.DOSTAWCY d ON p.IDDOSTAWCY = d.IDDOSTAWCY GROUP BY d.NAZWAFIRMY;

SELECT k.NAZWAFIRMY, count(z.IDKLIENTA) FROM ZAJECIA.ZAMOWIENIA z INNER JOIN zajecia.KLIENCI k ON z.IDKLIENTA = k.IDKLIENTA GROUP BY k.NAZWAFIRMY;

SELECT k.NAZWAFIRMY, count(z.IDKLIENTA) FROM ZAJECIA.ZAMOWIENIA z INNER JOIN zajecia.KLIENCI k ON z.IDKLIENTA = k.IDKLIENTA where k.AKTYWNY = 1 GROUP BY k.NAZWAFIRMY;

SELECT d.NAZWAFIRMY, count(p.IDPRODUKTU) FROM ZAJECIA.DOSTAWCY d INNER JOIN zajecia.PRODUKTY p ON d.IDDOSTAWCY = p.IDDOSTAWCY GROUP BY d.NAZWAFIRMY;

SELECT * FROM (
SELECT zam.DATAZAMOWIENIA, sum(op.CENAJEDNOSTKOWA * op.ILOSC) AS "Suma" 
FROM ZAJECIA.ZAMOWIENIA zam 
INNER JOIN zajecia.OPISY_ZAMOWIEN op 
ON zam.IDZAMOWIENIA = op.IDZAMOWIENIA GROUP BY zam.DATAZAMOWIENIA ORDER BY sum(op.CENAJEDNOSTKOWA * op.ILOSC) DESC)
WHERE rownum < 2;

SELECT k.NAZWAFIRMY, sum(o.CENAJEDNOSTKOWA * o.ILOSC) FROM ZAJECIA.KLIENCI k INNER JOIN ZAJECIA.ZAMOWIENIA z ON k.IDKLIENTA = z.IDKLIENTA INNER JOIN zajecia.OPISY_ZAMOWIEN o ON z.IDZAMOWIENIA = o.IDZAMOWIENIA GROUP BY k.NAZWAFIRMY;

SELECT DISTINCT DAY(z.DATAZAMOWIENIA), sum(o.CENAJEDNOSTKOWA * o.ILOSC) FROM ZAJECIA.ZAMOWIENIA z INNER JOIN zajecia.OPISY_ZAMOWIEN o ON z.IDZAMOWIENIA = o.IDZAMOWIENIA GROUP BY z.DATAZAMOWIENIA;
